geoscixyz/em

conf.py

added a creative commons license (by attribution) to the footer: http://creativecommons.org/licenses/by/4.0/

added CC-by-4.0 license to footer

---

AUTHORS.rst
README.md
content/equation_bank/ampere_maxwell_time.rst
content/equation_bank/faraday_time.rst
content/equation_bank/gauss_electric_time.rst
content/equation_bank/gauss_magnetic_time.rst
content/introduction/introduction_notation.rst
content/maxwell1_fundamentals/formative_laws_and_people/index.rst
content/maxwell1_fundamentals/fundamental_laws/ampere_maxwell.rst
content/maxwell1_fundamentals/fundamental_laws/conservation_of_charge.rst
content/maxwell1_fundamentals/fundamental_laws/faraday.rst
content/maxwell1_fundamentals/fundamental_laws/gauss_electric.rst
content/maxwell1_fundamentals/fundamental_laws/gauss_magnetic.rst
content/maxwell1_fundamentals/fundamental_laws/index.rst
content/maxwell1_fundamentals/index.rst
index.rst

- overview of Maxwell's equations
- template / outline for each of the fundamental laws
- sketch of ampere-maxwell (shows template for fundamental laws layout)

overview of MEI

---

content/maxwell1_fundamentals/fundamental_laws/conservation_of_charge.rst

Added charge conservation

---

conf.py
content/geophysical_surveys/index.rst
content/geophysical_surveys/looploopfdem/data.rst
content/geophysical_surveys/looploopfdem/field_acquisition.rst
content/geophysical_surveys/looploopfdem/governing_equations.rst
content/geophysical_surveys/looploopfdem/index.rst
content/geophysical_surveys/looploopfdem/interpretation.rst
content/geophysical_surveys/looploopfdem/practical_considerations.rst
content/geophysical_surveys/looploopfdem/survey_design.rst
index.rst

- loop loop fdem skeleton
- toc tree goes 3 deep on sidebar

Looploop fdem

---

autodoc.py
conf.py
content/equation_bank.rst
index.rst

auto-document the equation bank. when a new equation is added to the equation bank, the file equation_bank.rst will be updated. This has been added to the toctree after case_histories and before the references. 
closes #42

autodoc the equation bank

---

content/maxwell1_fundamentals/physical_principles/sources_in_a_homogeneous_medium/magnetic_dipole.rst

this notebook now lives in the ubcgif/em_examples repository

fix broken link to harmonic dipole notebook

---

conf.py

Add MIM and Cole Cole papers to linkcheck ignore - the link exists but are a bit unstable / slow

linkcheck ignore for papers

---

_templates/layout.html

add page source link to the footer in the new template

add source link to footer

---

_static/style.css
_templates/layout.html

Clean up the footer - include geosci home link as per #127

footer formatting - include page source and link to GeoSci home

---

content/case_histories/bookpurnong/interpretation.rst
content/case_histories/bookpurnong/setup.rst
content/case_histories/bookpurnong/synthesis.rst

A few typo fixes in the bookpurnong case history.

Aem edit typofixes

---

_ext/__init__.py
conf.py
content/maxwell1_fundamentals/maxwells_equations/time_domain_equations.rst

- fixed issue with broken link on line 41 of time_domain_equations.rst
- updated imports in conf.py so that testing will give more transparent errors. Local testing can be run by running `python test_docs.py` from em/tests

bug fixes on edits-fundamentalsWaveEqn

---

content/maxwell1_fundamentals/formative_laws/interface_conditions.rst

A few details:
- (detail 1)
- (detail 2)

Replace Luz website by Luz Github profile

---

content/case_histories/mt_isa/synthesis.rst

A few details:
- (detail 1)
- (detail 2)

Mt isa df kd

---

_ext/environmentSetup.py

- update suppress_nonlocal_image_warn to take kwargs so we get better sphinx warnings

improve error handling 

---

content/case_histories/mt_isa/index.rst

A few details:
- (detail 1)
- (detail 2)

added link

---

content/case_histories/mt_isa/properties.rst

MIM properties

---

content/case_histories/mt_isa/index.rst

updated text in prelude of MIM case history

MIM prelude updates

---

content/case_histories/mt_isa/survey.rst

MIM survey edits

---

content/case_histories/mt_isa/processing.rst

MIM Processing

---

content/case_histories/mt_isa/setup.rst

Minor grammar edit in mim case history

Mim minor grammar edit

---

content/case_histories/mt_isa/survey.rst

light mim edits

---

content/case_histories/mt_isa/interpretation.rst

doug's edits to interpretation

MIM interpretation.rst

---

content/case_histories/mt_isa/synthesis.rst

MIM synthesis.rst

---

app.yaml
emgeosci.py

upload source code for python examples

upload python source files to google app engine 

---

content/case_histories/mt_isa/interpretation.rst
content/case_histories/mt_isa/processing.rst

Fixed spelling and "Moondarra Shales"

---

content/case_histories/mt_isa/processing.rst
content/case_histories/mt_isa/survey.rst

A few details:
- (detail 1)
- (detail 2)

Add ling to survey design

---

contributors.json

A few details:
- (detail 1)
- (detail 2)

add contributor information

---

_static/css/style.css
_templates/layout.html
index.rst

- add an "Under Construction" section on index page
- add an "under construction note in the footer"

EM is under construction

---

conf.py
content/case_histories/index.rst

Remove bookpurnong case history from live site while it is under construction

take down bookpurnong from live case histories

---

content/geophysical_surveys/dcr/dcr_contents.html
content/geophysical_surveys/dcr/index.rst

patch internal links for the two column layout for dc

patch for internal links

---

underconstruction.html

better layout for the underconstruction box

---

contributors.json

I added a photo ^_^

---

content/geophysical_surveys/dcr/index.rst

A few details:
- (detail 1)
- (detail 2)

added comma

---

content/geophysical_surveys/dcr/physics.rst

A few details:
- (detail 1)
- (detail 2)

minor text changes

---

content/geophysical_surveys/dcr/interpretation.rst

typo fixes in interpretation

---

content/geophysical_surveys/dcr/data.rst
content/geophysical_surveys/dcr/index.rst
content/geophysical_surveys/dcr/interpretation.rst
content/geophysical_surveys/dcr/physics.rst
content/geophysical_surveys/dcr/survey.rst

Reread through DCR geophysical survey material and made spelling/grammar fixes.

Dc rsurveys sd

---

content/geophysical_surveys/dcr/physics.rst

DCR physics

---

content/geophysical_surveys/dcr/survey.rst

DCR Survey

---

content/case_histories/emc/index.rst

add author

---

content/geophysical_surveys/dcr/index.rst

...  to dipole-dipole figure so that it matches the text. This addresses Issue #246.

Updated schlumberger figure/text

---

.travis.yml

fix typos in the travis.yml so to fix the auto-deploy

typo in travis file

---

content/maxwell3_fdem/circuitmodel_for_eminduction/derive_response_function.rst
content/maxwell3_fdem/circuitmodel_for_eminduction/index.rst
content/maxwell3_fdem/circuitmodel_for_eminduction/understanding_harmonicEMresponse.rst
content/maxwell4_tdem/circuitmodel_for_eminduction/index.rst
content/maxwell4_tdem/circuitmodel_for_eminduction/synthesis_FDEMandTDEMresponse.rst
content/maxwell4_tdem/circuitmodel_for_eminduction/transientresponse.rst
content/maxwell4_tdem/circuitmodel_for_eminduction/understanding_trasientEMresponse.rst

Spell check for EM circuit model upon Issue #335

---

content/case_histories/aspen/survey.rst

Update survey Aspen

---

app.yaml

upload png, hires.png and pdf of plot_directive images
cc @thast

upload plot directive images

---

contributors.json
contributors.rst

Added @mikemcm to contributors. @mikemcm, if you are happy with this can you give a 👍 and I will merge it in? I grabbed your email as stated on your github profile

add Mike McMillan to Contributors

---

contributors.json
contributors.rst

add @rowanc1 to contributors. @rowanc1, can you give me a 👍 if you are good with this? I added your info and avatar based on your github profile

add rowan to contributors

---

contributors.json
contributors.rst

Add @krisdavis to contributors. @krisdavis, can you give me a 👍 if you are good with this? I used your photo from github. If you would like to add an email, just let me know which one to use!

Add Kris to contributors

---

content/geophysical_surveys/airborne_tdem/interpretation.rst
content/geophysical_surveys/airborne_tdem/skytem.rst
content/geophysical_surveys/airborne_tdem/survey.rst

Geop survey atem

---

app.yaml
emgeosci.py

- better handling of redirects for hitting index pages:
http://em.geosci.xyz/content/maxwell1_fundamentals/, 
http://em.geosci.xyz/content/maxwell1_fundamentals
now redirect to http://em.geosci.xyz/content/maxwell1_fundamentals/index.html

improve redirect handling for index pages

---

_templates/footer.html

Add links to 
- EM Home: http://em.geosci.xyz
- GeoSci.xyz: http://geosci.xyz
- Contact: http://geosci.xyz/contact

add links to geosci in the footer

---

content/case_histories/case_histories.json
content/case_histories/case_histories.rst
content/case_histories/kasted/index.rst
contributors.json
contributors.rst

SkyTEM people asked for some changes to authors list

Corrected authors for SkyTEM people

---

content/case_histories/case_histories.json
content/case_histories/case_histories.rst
content/case_histories/norsminde/index.rst

Norseminde authors2

---

_templates/footer.html
conf.py
content/equation_bank.rst
emgeosci.py
requirements.txt

this adds a comment thread to the bottom of each page of em geosci using disqus (https://disqus.com/) to allow posting of comments directly in the site
- privacy policy: https://help.disqus.com/customer/portal/articles/466259-privacy-policy
@dougoldenburg : I would appreciate your thoughts on this
For anyone interested in helping moderate / respond to comments, please let me know and I will add you on the disqus team!

add disqus to footer on each page

---

conf.py
content/case_histories/albany/index.rst
content/case_histories/aspen/index.rst
content/case_histories/balboa/index.rst
content/case_histories/barents_sea/index.rst
content/case_histories/bookpurnong/index.rst
content/case_histories/furggwanghorn/index.rst
content/case_histories/kasted/index.rst
content/case_histories/lalor/index.rst
content/case_histories/mt_isa/index.rst
content/case_histories/norsminde/index.rst
content/case_histories/wadi_sahba/index.rst
content/case_histories/westplains/index.rst

Added copywrite thank you for case histories in which permission was given.

Add copywrites1

---

app.yaml

use https by default on em geosci (addresses #513)

use https on em geosci

---

content/maxwell1_fundamentals/dipole_sources_in_homogeneous_media/magnetic_dipole_time/analytic_solution.rst

Equation \mathbf{\hat x} not included in the :math:` ` environment.

FIxed an equation format error

---

.github/workflows/python-app.yml

Remove duplicated branch check before deploying from Actions.

Remove duplicated check before deployment
